### DISCUSSION TITLE
How to run on k8s?

### DISCUSSION THREAD

**Discussion by khteh** [ChainSafe/lodestar#7361] [General]
When I run a k8s manifest using the latest docker container, the log shows:
```
$ k logs -f -p !$
k logs -f -p lodestar-0
🌟 Lodestar: TypeScript Implementation of the Ethereum Consensus Beacon Chain.

 * Version: v1.25.0/191f2f0
  * by ChainSafe Systems, 2018-2025

Commands:
  beacon       Run a beacon chain node
  validator    Run one or multiple validator clients
  lightclient  Run lightclient
  dev          Quickly bootstrap a beacon node and multiple validators. Use for
               development and testing
  bootnode     Run a discv5 bootnode. This will NOT perform any beacon node func
               tions, rather, it will run a discv5 service that allows nodes on
               the network to discover one another.

Options:
      --dataDir                             Lodestar root data directory[string]
      --network                             Name of the Ethereum Consensus chain
                                             network to join
  [string] [choices: "mainnet", "gnosis", "sepolia", "holesky", "chiado", "ephem
                                       ery", "mekong", "dev"] [default: mainnet]
      --paramsFile                          Network configuration file  [string]
      --rcConfig                            RC file to supplement command line a
                                            rgs, accepted formats: .yml, .yaml,
                                            .json                       [string]
      --terminal-total-difficulty-override  Terminal PoW block TTD override
                                                                        [string]
      --terminal-block-hash-override        Terminal PoW block hash override
                                                                        [string]
      --terminal-block-hash-epoch-override  Terminal PoW block hash override act
                                            ivation epoch               [string]
  -h, --help                                Show help                  [boolean]
  -v, --version                             Show version number        [boolean]

📖 For more information, check the CLI reference:
  * https://chainsafe.github.io/lodestar/reference/cli

✍️ Give feedback and report issues on GitHub:
  * https://github.com/ChainSafe/lodestar
```
Here is my container spec:
```
    spec:
      containers:
        - name: lodestar
          image: chainsafe/lodestar:v1.25.0
          imagePullPolicy: Always
          args:
            - --network holesky
            - --elClient geth
            - --dockerWithSudo
            - --detached
            - --withValidatorKeystore ~/lodestar-quickstart/
            - --withTerminal "gnome-terminal --disable-factory --"
            - --rest
            - --execution.urls="http://0.0.0.1:8551"
            - --rest.address 0.0.0.0
            - --rest.namespace '*'
            - --metrics
            - --logFile /logs/beacon.log
            - --jwtsecret=/tmp/jwtsecret
            - --dataDir=/data
```
It complains about the missing `command`. How do I pass the command to the container?
