### DISCUSSION TITLE
Command options as k8s ConfigMap?

### DISCUSSION THREAD

**Discussion by khteh** [ChainSafe/lodestar#7363] [General]
How to configure all the command options as k8s ConfigMap?
```
      containers:
        - name: lodestar
          image: chainsafe/lodestar:v1.25.0
          imagePullPolicy: Always
          args:
            - beacon
            - --network=holesky
            - --dataDir="/data"
            - --eth1=true
            - --execution.urls="http://0.0.0.1:8551"
            - --jwtSecret="/tmp/jwtsecret"
            - --rest
            - --rest.address=0.0.0.0
            - --rest.namespace='*'
            - --metrics
            - --logFile="/logs/beacon.log"
```
I would love these to be organized into ConfigMap instead of in the STS manifest.

**Comment by nflaig** [comment]
you can pass the config via file, `--rcConfig config.yml`

it looks like this
```yaml
network: mainnet
rest: true
rest.address: 0.0.0.0
rest.port: 9596
# ...
```

this should work well with `ConfigMap`

**Reply by khteh** [reply]
This sounds good. How about the first "option" - `beacon`?

**Reply by khteh** [reply]
And `--metrics`

**Reply by nflaig** [reply]
> This sounds good. How about the first "option" - beacon

you would just add that to the command, I would recommend to use to different container definitions for beacon and validator anyways, and you would need two different configmaps as well since the flags are different

**Reply by nflaig** [reply]
> And --metrics

any CLI flag works
```yaml
metrics: true
```

**Reply by khteh** [reply]
I don't have `command`  in the manifest.  I am not sure what do you mean "different container definitions for beacon and validator". Currently, I start the validator in `postStart` since I don't find any reference how to run both the beacon and validator on k8s.

**Reply by nflaig** [reply]
>  "different container definitions for beacon and validator"

just 2 different containers in your cluster, I guess in k8s terms would be two `Deployment` definitions which create a separate set of pods, for validator specifically you need to make sure to only have a single instance running

**Reply by khteh** [reply]
This sounds like running 2 separate ldestar applications in different modes. How about the k8s headless service in this configuration?

**Reply by nflaig** [reply]
I would recommend to look at the k8s helm charts and see how Lodestar is configured here https://github.com/ethpandaops/ethereum-helm-charts/tree/master/charts/lodestar, and maybe adapt it to your needs

**Reply by khteh** [reply]
Are the ports arbitrary or fixed to the following?
```
# -- P2P Port
p2pPort: 9000

# -- HTTP Port
httpPort: 9596

# -- Metrics Port
metricsPort: 8008
```

**Reply by nflaig** [reply]
you can change the values if you want to but make sure to use right keys in the yaml file, eg. it's `metrics.port` same as CLI flag, you can find those in the CLI reference docs

**Reply by khteh** [reply]
I run with the following command in the STS manifest:
```
    spec:
      containers:
        - name: lodestar
          image: chainsafe/lodestar:v1.25.0
          imagePullPolicy: IfNotPresent
          command:
            - ./lodestar
            - beacon
            - --rcConfig
            - /tmp/beacon-config.yml
          volumeMounts:
            - name: beacon-config
              mountPath: /tmp/beacon-config.yml
              subPath: beacon-config.yml
              readOnly: true
      volumes:
        - name: beacon-config
          configMap:
            name: beacon-config
```
and hit the following error:
```
$ k logs -f lodestar-beacon-0
 ✖ YError: EISDIR: illegal operation on a directory, read
    at file:///usr/app/node_modules/yargs/build/lib/yargs-factory.js:1478:23
    at file:///usr/app/node_modules/yargs/build/lib/command.js:194:17
    at maybeAsyncResult (file:///usr/app/node_modules/yargs/build/lib/utils/maybe-async-result.js:9:15)
    at CommandInstance.handleValidationAndGetResult (file:///usr/app/node_modules/yargs/build/lib/command.js:193:25)
    at CommandInstance.applyMiddlewareAndGetResult (file:///usr/app/node_modules/yargs/build/lib/command.js:245:20)
    at CommandInstance.runCommand (file:///usr/app/node_modules/yargs/build/lib/command.js:128:20)
    at YargsInstance.[runYargsParserAndExecuteCommands] (file:///usr/app/node_modules/yargs/build/lib/yargs-factory.js:1386:105)
    at YargsInstance.parse (file:///usr/app/node_modules/yargs/build/lib/yargs-factory.js:707:63)
    at file:///usr/app/packages/cli/src/index.ts:29:4
```
