### ISSUE TITLE
WebAssembly.Instance(): Out of memory: wasm memory

### ISSUE THREAD

**Issue by mgcrea** [ChainSafe/lodestar#1427]
**Describe the bug**

Running via docker-compose with 10G ulimits triggers an OOM error on startup

**Expected behavior**

Support ulimits

**Steps to Reproduce**

```yml
version: "3.2"
services:
  beacon:
    image: chainsafe/lodestar:latest
    restart: always
    container_name: lodestar_beacon
    hostname: lodestar_beacon
    environment:
      - TZ=${TZ}
    ports:
      - "9000:9000"
    volumes:
      - "./volumes/beacon:/data"
    command:
      - beacon
      - --rootDir=/data
      - --eth1.enabled
      - --eth1.provider.url=http://geth_goerli.geth_default:8545
      - --metrics.enabled
      - --testnet=medalla
    networks:
      - default
      - geth
    ulimits:
      as:
        hard: 10000000000
        soft: 10000000000

networks:
  geth:
    external:
      name: geth_default
```

**Screenshots**

```
beacon_1     | /usr/app/node_modules/@assemblyscript/loader/index.js:303
beacon_1     |     new WebAssembly.Instance(
beacon_1     |     ^
beacon_1     | RangeError: WebAssembly.Instance(): Out of memory: wasm memory
beacon_1     |     at Object.instantiateSync (/usr/app/node_modules/@assemblyscript/loader/index.js:303:5)
beacon_1     |     at newInstance (/usr/app/node_modules/@chainsafe/as-sha256/lib/wasm.js:20:26)
beacon_1     |     at new SHA256 (/usr/app/node_modules/@chainsafe/as-sha256/lib/index.js:12:38)
beacon_1     |     at Object.<anonymous> (/usr/app/node_modules/@chainsafe/as-sha256/lib/index.js:61:14)
beacon_1     |     at Module._compile (internal/modules/cjs/loader.js:959:30)
beacon_1     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
beacon_1     |     at Module.load (internal/modules/cjs/loader.js:815:32)
beacon_1     |     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
beacon_1     |     at Module.require (internal/modules/cjs/loader.js:852:19)
beacon_1     |     at require (internal/modules/cjs/helpers.js:74:18)
```

**Desktop (please complete the following information):**

```
docker run -it --rm chainsafe/lodestar:latest --version
0.11.0
```
