### ISSUE TITLE
Implement Deposit according to spec 0.7.1

### ISSUE THREAD

**Issue by sadiq1971** [ChainSafe/lodestar#268]
current data Structure for Deposit-
````class Deposit(Container):
    # Branch in the deposit tree
    proof: Vector[Bytes32, DEPOSIT_CONTRACT_TREE_DEPTH]
    # Index
    index: uint64
    # Data
    data: DepositData
````
according to 0.7.1 spec modify deposit throughout the project
````
class Deposit(Container):
    # Branch in the deposit tree
    proof: Vector[Bytes32, DEPOSIT_CONTRACT_TREE_DEPTH]
    # Data
    data: DepositData
previous:
````
