### ISSUE TITLE
altair-devnet-2: Invalid signature SignedAggregateAndProof at the fork slot

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#2908]
**Describe the bug**

From Teku:

"At the same time I got the following invalid signed aggregate and proof (which I think comes from a lodestar validator):"
```
0x64000000b80c5d8233733f9684fef1edee56603df7cf4700d13e9532c338fac1fcbe2886209c94490e09082430a94d0bdaf04ad11827be97358d114dece6b81c298ff427294d64d7efab8b19eaacb6a77916931770aaed3eeafa4d6b93573c271e4377e86e290000000000006c00000093a901006eaf8c2e5d8ea94939d631247984180c4faad3e3646ca112c467e419a2f7308fc5abc79ba99a07999362b1c30ec28bccbfd7bd0a60f58a2fab272edb0256309219eff2493e7ea52b7d73ce2dc0bbac27120d7997d9a6944e3a1e4255e40000004001000000000000020000000000000039998ed61f601fed3e21059e7f99dfc31a5ee8ecb34e22e2790f09095397997d0900000000000000b523c2bc822f304369018e505920e3f5451b0616fb2b6750eaeb5273f76f72050a0000000000000039998ed61f601fed3e21059e7f99dfc31a5ee8ecb34e22e2790f09095397997db945ebbf87891cd5c47df4c7110282948b129bb56fb73d570ce3c05cad7db58592f477669996d086e73d73ebf7c850c10828071f3b54a7e24a9868072197df6bd90c59fa0322b718d055044ed4d91cff5756f328430e70dca1d6824bb4df5f2730000122c07600a040604000420000700001
```

This is decoded at:
```yaml
message:
  aggregatorIndex: '10606'
  aggregate:
    aggregationBits: '0x30000122c07600a040604000420000700001'
    data:
      slot: '320'
      index: '2'
      beaconBlockRoot: '0x39998ed61f601fed3e21059e7f99dfc31a5ee8ecb34e22e2790f09095397997d'
      source:
        epoch: '9'
        root: '0xb523c2bc822f304369018e505920e3f5451b0616fb2b6750eaeb5273f76f7205'
      target:
        epoch: '10'
        root: '0x39998ed61f601fed3e21059e7f99dfc31a5ee8ecb34e22e2790f09095397997d'
    signature: >-
      0xb945ebbf87891cd5c47df4c7110282948b129bb56fb73d570ce3c05cad7db58592f477669996d086e73d73ebf7c850c10828071f3b54a7e24a9868072197df6bd90c59fa0322b718d055044ed4d91cff5756f328430e70dca1d6824bb4df5f27
  selectionProof: >-
    0x93a901006eaf8c2e5d8ea94939d631247984180c4faad3e3646ca112c467e419a2f7308fc5abc79ba99a07999362b1c30ec28bccbfd7bd0a60f58a2fab272edb0256309219eff2493e7ea52b7d73ce2dc0bbac27120d7997d9a6944e3a1e4255
signature: >-
  0xb80c5d8233733f9684fef1edee56603df7cf4700d13e9532c338fac1fcbe2886209c94490e09082430a94d0bdaf04ad11827be97358d114dece6b81c298ff427294d64d7efab8b19eaacb6a77916931770aaed3eeafa4d6b93573c271e4377e8

```

**Expected behavior**

Lodestar should produce valid SignedAggregateAndProof at the fork slot
