### ISSUE TITLE
Lodestar fell out of sync on MainNet

### ISSUE THREAD

**Issue by ajsutton** [ChainSafe/lodestar#3247]
**Describe the bug**

Lodestar running in docker, initially sync'd correctly with checkpoint sync and then was correctly tracking head but after a while started listing all slots as empty then went back to sync mode and failed to recover.

**Expected behavior**

Lodestar should remain in sync with chain.

**Steps to Reproduce**

Ran Lodestar with the docker-compose config:
```
lodestar-mainnet:
    image: chainsafe/lodestar
    volumes:
      - './lodestar/mainnet:/data'
    command:
      - 'beacon'
      - '--rootDir'
      - '/data/beacon'
      - '--network'
      - 'mainnet'
      - '--weakSubjectivityServerUrl'
      - 'https://<credentials>@eth2-beacon-mainnet.infura.io'
      - '--weakSubjectivitySyncLatest'
      - '--logFile'
      - '/data/lodestar.log'
      - '--api.rest.enabled'
      - '--api.rest.host'
      - '0.0.0.0'
      - '--metrics.enabled'
      - '--network.discv5.bindAddr'
      - '/ip4/0.0.0.0/udp/9100'
      - '--network.localMultiaddrs'
      - '/ip4/0.0.0.0/tcp/9100'
    ports:
      - "9100:9100/tcp"
      - "9100:9100/udp"
      - "9596:9596"
```

I did wind up restarting it a couple of times after it was first in sync.  On the last run it caught up to head again but then failed to remain in sync.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mac OS 11.6 (but using `chainsafe/lodestar` docker image
- Version:  
``` 
🌟 Lodestar: TypeScript Implementation of the Ethereum 2.0 Beacon Chain.
  * Version: v0.30.0 (npm)
  * by ChainSafe Systems, 2018-2021
```
- Branch: master
Docker image ID: `805bbdf546b0`
