### ISSUE TITLE
lodestar doesn't run using docker on Apple Silicon Mac

### ISSUE THREAD

**Issue by hiromaily** [ChainSafe/lodestar#4801]
I tried to run lodestar node as dev mode using docker according to docs about [localnet](https://chainsafe.github.io/lodestar/usage/local/)
However, it didn't run and `exited with code 139` occurred.

I tried the same at Intel Mac and it worked.

**Describe the bug**
`exited with code 139` happened 

**Expected behavior**
no error

**Steps to Reproduce**
my container setting is
```
  lodestar-localnet:
    image: 'chainsafe/lodestar:v1.2.1'
    container_name: lodestar-localnet
    volumes:
      - ./data/lodestar:/data
    ports:
      - "9000:9000" # P2P port
      - "9596:9596" # REST API port
    command:
      - dev
      - --genesisValidators
      - "2"
      - --startValidators
      - "0..1"
      - --genesisTime
      - "1578787200"
      - --enr.ip
      - 127.0.0.1
      - --dataDir
      - /data
      - --reset
```
and just run `docker compose up lodestar-localnet`

**Screenshots**

**Desktop (please complete the following information):**

- OS:  MacOS / Apple M2 chip
- Version:  12.6
- Branch:  docker image: v1.2.1
- Commit hash:
