### ISSUE TITLE
Dashboard metrics using `scrape_location` label in expression are broken

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#4809]
**Problem**

At the moment all dashboard metrics which use the label `scrape_location` in the expression are broken because this label is not set anywhere. Currently the expected label values used in the dashboards are either `validator` or `beacon`.

**Possible solutions**

I see three options how this could be fixed

1. set `scrape_location` as [default label](https://github.com/siimon/prom-client#default-labels-segmented-by-registry)
2. use `job` name or `instance` to differentiate between beacon node and validator
3. set it in `prometheus.yml` file
```
    static_configs:
      - targets: ["localhost:8008"]
        labels:
          scrape_location: "beacon"
```

In my opinion option 1. is the best solution because it does not rely on the deployment configuration.

**Screenshots**

![image](https://user-images.githubusercontent.com/38436224/203752419-b2727722-4010-40f1-bcee-887bce077c40.png)
