### ISSUE TITLE
Unconfigured Grafana panel "Panel Title" in lodestar_summary.yml

### ISSUE THREAD

**Issue by aaronmboyd** [ChainSafe/lodestar#5934]
### Describe the bug

There is a blank panel configuration in the Lodestar summary dashboard configuration with title "Panel Title". It is not connected to any datasource or query metric, and the chart that is rendered is literally just random timeseries: query source is Grafana/Random Walk.

### Expected behavior

Should be removed or updated with relevant metric if it's a placeholder.

### Steps to reproduce

N/A

### Additional context

![image](https://github.com/ChainSafe/lodestar/assets/13218496/4f668d29-1f7c-4c6b-ab63-707d5b530d6b)

### Operating system

Linux

### Lodestar version or commit hash

v1.10.0

**Comment by nflaig** [comment]
This is definitely something we should fix, we could just remove the panel but I think we could also use the opportunity to add few more metrics and rework the dashboard a bit.

The Lodestar summary dashboard should be tailored towards node operators as it is the dashboard that comes by default in solutions like eth-docker and  dappnode. It is also not really used by client devs as other dashboards usually provide better and more detailed insights.

We could for example add validator performance metrics, e.g. we have a panel that tracks metrics based on formula used by [rated.network](https://www.rated.network/). Maybe @aaronmboyd you have some metrics in mind you would like to see there.

**Comment by aaronmboyd** [comment]
Well, the bug report was more that a release tagged version contains placeholder or erroneous panels.

This is important to me as a solo validator, because I provision the dashboards directly to my grafana instance (containerized) by mapping the git repo / dashboards folder to my grafana container, then auto-loading these boards with the mapped config file:
```
apiVersion: 1

providers:
  - name: "Dashboard provider from docker compose"
    orgId: 1
    folder: "Lodestar Presets"
    type: file
    disableDeletion: false
    updateIntervalSeconds: 10
    allowUiUpdates: true
    options:
      path: /var/lib/grafana/dashboards
      foldersFromFilesStructure: false
```
So I treat the contents of `dashboards` as they are, and assume that tagged versions (not unstable) will be feature complete. Periodically I update the repo to a new tag and then bounce the grafana container and it will pick up the new dashboards.

Re: What validators would like to see on the dashboards:  I would like to see more documentation or clarity on the job name mapping. It's not immediately obvious that the boards are expecting `beacon` and `validator` all over the place, and this makes it hard where you have a datasource with multiple consensus / validators. (I have Goerli and mainnet setup and collecting from the same datasource, for example).

Would also love to see more "effectiveness" measures as suggested above. I observe the beaconcha.in validator page and have no idea how they evaluate "Effectiveness". Would also be interested in something that can visualise MEV or execution rewards. Perhaps even withdrawal address monitoring?

The Lodestar team dashboards are actually really great as they are, much more detailed and clear than say, Besu's default boards in my opinion.

**Comment by nflaig** [comment]
Thanks for the feedback @aaronmboyd

> tagged versions (not unstable) will be feature complete

This should be the case as dashboards are versioned with the source code it is ensured those work together well.

> Re: What validators would like to see on the dashboards: I would like to see more documentation or clarity on the job name mapping. It's not immediately obvious that the boards are expecting beacon and validator all over the place

I agree here, it is not ideal but we need some way to differentiate between beacon and validator as some metric names are duplicated such as process metrics. I already looked at this problem and one solution for this was to give the user the option to configure the job name via a variable when importing the dashboard (https://github.com/ChainSafe/lodestar/pull/5211). In this case it would be more obvious for a user that those names are relevant and you would not have to change your prometheus scrape config but if you use auto provisioning, this unfortunately does not work. Highlighting this somewhere in our documentation would definitely help.

> Would also love to see more "effectiveness" measures as suggested above. I observe the beaconcha.in validator page and have no idea how they evaluate "Effectiveness". Would also be interested in something that can visualise MEV or execution rewards. Perhaps even withdrawal address monitoring?

Sounds good, will see what we can do here

**Comment by aaronmboyd** [comment]
Regarding differentiating between beacon and validator, I think it's too simplistic to rely on job name, it really forces you to make a new datasource for each environment. How about a solution, like this (prometheus.yml):

```
  - job_name: mainnet-consensus-lodestar #user defined
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - 10.10.10.1:5054
      labels:
        instance: mainnet #user defined
        service: consensus #mandatory

  - job_name: mainnet-validator-lodestar #user defined
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - 10.10.10.2:5056
      labels:
        instance: mainnet #user defined
        service: validator #mandatory

  - job_name: goerli-consensus-lodestar #user defined
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - 10.10.10.3:5054
      labels:
        instance: goerli #user defined
        service: consensus #mandatory

  - job_name: goerli-validator-lodestar #user defined
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - 10.10.10.4:5056
      labels:
        instance: goerli #user defined
        service: validator #mandatory
```

So the solution there is to add `instance` and `service` as variables/filters to each dashboard and update the default/example prometheus.yml in the repo. Or, a different solution:

```
  - job_name: goerli-validator-lodestar #user defined
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - 10.10.10.4:5056
      labels:
        instance: goerli #user defined
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'lodestar_validator_(.*)' # mandatory if you want to tag this as a Lodestar validator
        target_label: __name__
        replacement: '$1'
```

Then the dashboards only ever look for `lodestar_validator...` or `lodestar_consensus...`? Keep `instance` filter on each dashboard.

Finally... I would prefer moving to the naming `consensus` as `beacon` has fallen out of favour a little.

**Comment by nflaig** [comment]
> I think it's too simplistic to rely on job name, it really forces you to make a new datasource for each environment

Using `job` label is strictly better than adding a custom label like `service` as it exists by default and can be configured when importing the dashboard, no modification of prometheus config is required, which was the main goal of https://github.com/ChainSafe/lodestar/pull/5211.

> So the solution there is to add instance and service as variables/filters to each dashboard and update the default/example prometheus.yml in the repo

`job` is really just a standardized label added by prometheus, you can easily override it

```yml
- job_name: goerli-validator-lodestar #user defined
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - 10.10.10.4:5056
      labels:
        instance: goerli #user defined
        job: validator # <-- in case your job_name is different, override job label here
```

> Finally... I would prefer moving to the naming consensus as beacon has fallen out of favour a little.

I am not so sure about this, in my mind, using the term "beacon" is more technically accurate / less ambiguous. If I use the term "consensus client" I usually refer to the complete implementation (beacon node + validator client) as the beacon node itself can not actively participate in consensus (sign attestations, propose blocks, etc.).
