### ISSUE TITLE
Eventstream API light client events spec compatibility

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#6197]
### Describe the bug

Currently Lodestar does not return light client events as defined in spec examples [beacon-APIs/#/Events/eventstream](https://ethereum.github.io/beacon-APIs/#/Events/eventstream).

The [spec example](https://github.com/ethereum/beacon-APIs/blob/6559c852193b14a33ddcb1ba770db29d62a52878/apis/eventstream/index.yaml#L98-L102) has an additional version field and wrapps the actual light client updates into data layer (similar to REST API)
```yaml
            light_client_finality_update:
              description: The node's latest known `LightClientFinalityUpdate` has been updated
              value: |
                event: light_client_finality_update
                data: {"version":"phase0", "data": {"attested_header": {"beacon": { ... }}
```

This incompatibility causes issues as Lodestar and Nimbus beacon node return different data formats.
- https://lodestar-mainnet.chainsafe.io/eth/v1/events?topics=light_client_optimistic_update
- http://testing.mainnet.beacon-api.nimbus.team/eth/v1/events?topics=light_client_optimistic_update

This was brought up by @rdvorkin at the Light Client Summit at Devconnect in [Building a trustless light-client assistant in your browser](https://app.streameth.org/devconnect/light_client_summit/session/remote_presenter_building_a_trustless_lightclient_assistant_in_your_browser) around 11:30

![image](https://github.com/ChainSafe/lodestar/assets/38436224/f0f50787-d98e-4076-a463-2255793ecf28)

Other issues that @jeluard brought up about the light client event examples
- version is `phase0` whereas light client was introduced in `altair` (fails our spec tests)
- `sync_committee_bits` too short

We should clarify if the current format as outlined in the spec should be the standard or we want to omit version and data layer. Other events do not use a data layer in the serialized json which makes the light client events a bit of an outlier.

### Additional context

We currently just calculate the fork version based on slot in attested header
```python
compute_fork_version(compute_epoch_at_slot(data.attested_header.beacon.slot))
```

https://github.com/ChainSafe/lodestar/blob/c044d4cdd484a7e5ac90e83169955bd6e4697063/packages/api/src/beacon/routes/events.ts#L213

### Related

Testing Lodestar events API against the spec examples causes issues as well and we have to ignore those topics during testing
- https://github.com/ChainSafe/lodestar/issues/6170

Beacon-API spec PR (there was no discussion around events format)
- https://github.com/ethereum/beacon-APIs/pull/247
