### ISSUE TITLE
Too many unknown peers in test mainnet nodes

### ISSUE THREAD

**Issue by twoeths** [ChainSafe/lodestar#6382]
### Describe the bug

There are too many unknown peers in test mainnet nodes

<img width="1331" alt="Screenshot 2024-01-31 at 09 12 58" src="https://github.com/ChainSafe/lodestar/assets/10568965/0d50270b-a0cd-4e6e-af35-907b1d177323">

this does not happen to nodes with connected validators

### Expected behavior

Should investigate who they are, are they useless to lodestar or not

### Operating system

Linux

### Lodestar version or commit hash

v1.15.0

**Comment by twoeths** [comment]
`curl http://localhost:9596/eth/v1/lodestar/peers` shows too many `NA` peers, which means `agentVersion` is not set for them https://github.com/ChainSafe/lodestar/blob/v1.15.0/packages/beacon-node/src/network/peers/peersData.ts#L38

**Comment by twoeths** [comment]
looks like it caused by this one https://github.com/ChainSafe/lodestar/pull/6028/files#diff-e50e7caad2bee8b503fd63320dbc6c32e9f90f05aa76b211df989d02030a9aa6R613

it's supposed to get agent version after 1s but right now we try to get agent version immediately right after a `peer:connect` event cc @nazarhussain

**Comment by wemeetagain** [comment]
@libp2p/identify now provides a way to manually trigger identify calls. We should use that rather than waiting X seconds and hoping that an identify happened.

should look something like:
```ts
libp2p.identify.identify(peerId).then((i) => {
  const agentVersionBytes = i.AgentVersion
  ...
}).catch(...);
```

We also need to configure the identify module to not automatically trigger identify too.
```ts
createLibp2p({
  identify: identify({... // something here
```

**Comment by nazarhussain** [comment]
@wemeetagain Looking forward to work on this issue after we release the fix you made https://github.com/libp2p/js-libp2p/pull/2387

**Comment by twoeths** [comment]
in kurtosis devnet-0, this is my config
```yml
participants:
  - el_type: nethermind
    el_image: 192.168.45.152:80/dh/nethermindeth/nethermind:pectra
    cl_type: lodestar
    cl_image: 192.168.45.152:80/dh/ethpandaops/lodestar:electra-fork
    count: 1
  - el_type: ethereumjs
    el_image: 192.168.45.152:80/dh/ethpandaops/ethereumjs:master
    cl_type: grandine
    cl_image: 192.168.45.152:80/dh/ethpandaops/grandine:feature-electra
    count: 1
  - el_type: geth
    el_image: 192.168.45.152:80/dh/ethpandaops/geth:lightclient-prague-devnet-0
    cl_type: teku
    cl_image: 192.168.45.152:80/dh/ethpandaops/teku:master
    count: 1
  - el_type: geth
    el_image: 192.168.45.152:80/dh/ethpandaops/geth:lightclient-prague-devnet-0
    cl_type: lighthouse
    cl_image: 192.168.45.152:80/dh/ethpandaops/lighthouse:ef-tests-electra
    count: 1
network_params:
  electra_fork_epoch: 1
  seconds_per_slot: 12
  num_validator_keys_per_node: 64
snooper_enabled: true
additional_services:
  - tx_spammer
  - blob_spammer
  - el_forkmon
  - beacon_metrics_gazer
  - dora
  - prometheus_grafana
```

metric:
<img width="729" alt="Screenshot 2024-05-15 at 11 02 04" src="https://github.com/ChainSafe/lodestar/assets/10568965/b6e0dbfc-47f7-4c47-bbfe-ef25f500dbe9">

we can't detect Grandine and Lighthouse @nazarhussain
