### ISSUE TITLE
Eth-Consensus-Version header is missing in publish block requests

### ISSUE THREAD

**Issue by nflaig** [ChainSafe/lodestar#6580]
### Describe the bug

The spec requires to set Eth-Consensus-Version header in publish block requests

[blocks.v2.yaml#L39-L44](https://github.com/nflaig/beacon-APIs/blob/425824e42ff55a4e3c06ab2d434232d8ea2b543e/apis/beacon/blocks/blocks.v2.yaml#L39-L44)
```yaml
    - in: header
      schema:
        $ref: '../../../beacon-node-oapi.yaml#/components/schemas/ConsensusVersion'
      required: true
      name: Eth-Consensus-Version
      description: "Version of the block being submitted."
```

While Lodestar itself uses the request payload to determine the fork type from `data.message.slot` other clients like Prysm BN require this header to be set.

https://github.com/ChainSafe/lodestar/blob/129f300d143b0447978e06e575f9a2c7c31d7b26/packages/api/src/beacon/routes/beacon/block.ts#L296-L298

### Expected behavior

Set all headers as required by the spec

### Operating system

Linux

### Lodestar version or commit hash

v1.17.0
