### ISSUE TITLE
`./lodestar validator ...` hits `Error: EROFS: read-only file system, mkdir ` error

### ISSUE THREAD

**Issue by khteh** [ChainSafe/lodestar#7362]
### Describe the bug

I am running `lodestar` as  k8s STS with the keystore ConfigMap mounted to `/tmp/keystores` directory. Running the validator hits the following error:
```
root@lodestar-0:/usr/app# ./lodestar validator --network holesky --dataDir=/data --importKeystores /tmp/keystores --importKeystoresPassword /tmp/password.txt
Jan-15 07:35:14.821[]                 info: Lodestar network=holesky, version=v1.25.0/191f2f0, commit=191f2f0ac71d4f660d1ffbd04044a58de114c049
Jan-15 07:35:14.823[]                 info: Connecting to LevelDB database path=/data/validator-db
 ✖ Error: EROFS: read-only file system, mkdir '/tmp/keystores/..2025_01_15_07_34_31.4293813640/keystore-m_12381_3600_0_0_0-1736913052.json.lock'
    at Object.mkdirSync (node:fs:1364:26)
    at Object.newFs.<computed> [as mkdir] (/usr/app/node_modules/proper-lockfile/lib/adapter.js:15:42)
    at acquireLock (/usr/app/node_modules/proper-lockfile/lib/lockfile.js:29:16)
    at RetryOperation._fn (/usr/app/node_modules/proper-lockfile/lib/lockfile.js:233:13)
    at RetryOperation.attempt (/usr/app/node_modules/retry/lib/retry_operation.js:112:8)
    at /usr/app/node_modules/proper-lockfile/lib/lockfile.js:232:19
    at resolveCanonicalPath (/usr/app/node_modules/proper-lockfile/lib/lockfile.js:17:16)
    at lock (/usr/app/node_modules/proper-lockfile/lib/lockfile.js:224:5)
    at /usr/app/node_modules/proper-lockfile/lib/adapter.js:53:9
    at lockSync (/usr/app/node_modules/proper-lockfile/index.js:13:42)
root@lodestar-0:/tmp/keystores# ls -al
total 12
drwxrwxrwx 3 root root 4096 Jan 15 07:34 .
drwxrwxrwt 1 root root 4096 Jan 15 07:34 ..
drwxr-xr-x 2 root root 4096 Jan 15 07:34 ..2025_01_15_07_34_31.4293813640
lrwxrwxrwx 1 root root   32 Jan 15 07:34 ..data -> ..2025_01_15_07_34_31.4293813640
lrwxrwxrwx 1 root root   50 Jan 15 07:34 keystore-m_12381_3600_0_0_0-1736913052.json -> ..data/keystore-m_12381_3600_0_0_0-1736913052.json
root@lodestar-0:/tmp/keystores# 
```
My manifest portion of the ConfigMap mount:
```
          volumeMounts:
            - name: validator-keystore
              mountPath: /tmp/keystores
              readOnly: false
      volumes:
        - name: validator-keystore
          configMap:
            name: validator-keystore
            defaultMode: 0755
```
This happens because ConfigMap is mounted RO.

### Expected behavior

No error!

### Operating system

Linux

### Lodestar version or commit hash

v1.25.0
