### ISSUE TITLE
Beacon API not populating p2p_addresses with correct IP address

### ISSUE THREAD

**Issue by barnabasbusa** [ChainSafe/lodestar#7798]
### Describe the bug

When running in kurtosis with public IP being exposed, the p2p_address field in the beacon api endpoint (`/eth/v1/node/identity`) reports the container's IP address instead of the exposed IP address.

It will generate a correct enr, that has the ip and the port, but it when doing a local query it will return:

```json
{
  "data": {
    "peer_id": "16Uiu2HAmSaymcGxatuTFbSftga1FYCe4v9eDKyEzsePoSiPABSd7",
...
    "p2p_addresses": [
      "/ip4/127.0.0.1/tcp/33000/p2p/16Uiu2HAmSaymcGxatuTFbSftga1FYCe4v9eDKyEzsePoSiPABSd7",
      "/ip4/172.16.0.7/tcp/33000/p2p/16Uiu2HAmSaymcGxatuTFbSftga1FYCe4v9eDKyEzsePoSiPABSd7"
    ],
    ...
}

### Expected behavior

I would expect the p2p_addresses filed to be populated with the public IP address as well, instead of the docker container's local ip address.


```json
{
  "data": {
    "peer_id": "16Uiu2HAmSaymcGxatuTFbSftga1FYCe4v9eDKyEzsePoSiPABSd7",
...
    "p2p_addresses": [
      "/ip4/127.0.0.1/tcp/33000/p2p/16Uiu2HAmSaymcGxatuTFbSftga1FYCe4v9eDKyEzsePoSiPABSd7",
      "/ip4/93.22.22.204/tcp/33000/p2p/16Uiu2HAmSaymcGxatuTFbSftga1FYCe4v9eDKyEzsePoSiPABSd7"
    ],
    ...
}
```

### Steps to reproduce

Run kurtosis with:
```yaml
participants:
  - count: 1
    cl_type: lodestar
network_params:
  network: mainnet
persistent: true

port_publisher:
  nat_exit_ip: 93.22.22.204 #(or whatever public IP you've got)
  cl:
    enabled: true
    public_port_start: 33000
```

This will run lodestar with the following flags:
```
                "--nat=true",
                "--enr.ip=93.22.22.204",
                "--enr.tcp=33000",
                "--enr.udp=33000",
```

### Operating system

Linux

### Lodestar version or commit hash

v1.19.0
