### ISSUE TITLE
Integer overflow for withdrawals with more than 9M eth

### ISSUE THREAD

**Issue by barnabasbusa** [ChainSafe/lodestar#7892]
### Describe the bug

Non critical bug to report, if you try to do a withdrawal with a balance over 2^53 - 1 ~9M then lodestar will break. 

### Expected behavior

Don't break :D 

### Steps to reproduce

kurtosis:
This works:
```yaml
participants:
  - cl_type: lighthouse
  - cl_type: lodestar
network_params:
  withdrawal_type: "0x01"
  validator_balance: 9000000
```
This doesn't work anymore:
```yaml
participants:
  - cl_type: lighthouse
  - cl_type: lodestar
network_params:
  withdrawal_type: "0x01"
  validator_balance: 9007300
```

### Operating system

Linux

### Lodestar version or commit hash

latest
