### ISSUE TITLE
Not able to run lodestar in kubernetes with services

### ISSUE THREAD

**Issue by worldwideward** [ChainSafe/lodestar#7925]
### Describe the bug

When I deploy lodestar to kubernetes as a statefulset, and apply a service for port 9000, the container crashes with the message:

```
✖ Unknown arguments: port9000TcpProto, serviceHost, port9000TcpPort, servicePort, servicePortPeers, port9000TcpAddr, servicePort Rest
```

When I delete `service.yml` the workload runs fine.

### Expected behavior

The node should run and port 9000 should be reachable through the service

### Steps to reproduce

`k apply -f service.yml`
```
---
apiVersion: v1
kind: Service
metadata:
  name: lodestar
spec:
  selector:
    app: lodestar
  type: NodePort
  ports:
  - protocol: TCP
    port: 9000
    nodePort: 30900
    name: peers
```

`k apply -f statefulset.yml`
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lodestar-gnosis
  labels:
    app: lodestar
spec:
  replicas: 1
  serviceName: lodestar
  selector:
    matchLabels:
      role: beacon
  template:
    metadata:
      labels:
        role: beacon
    spec:
      volumes:
      - name: secrets
        secret:
          secretName: jwt
      containers:
        - name: lodestar
          image: chainsafe/lodestar:v1.31.0
          args:
          - "beacon"
          - "--network"
          - "chiado"
          - "--execution.urls"
          - "http://execution-node:8551"
          - "--dataDir"
          - "/data"
          - "--jwt-secret"
          - "/secrets/jwt.hex"
          - "--checkpointSyncUrl"
          - "https://checkpoint.chiadochain.net/"
          volumeMounts:
            - name: secrets
              mountPath: /secrets
```

### Operating system

Linux

### Lodestar version or commit hash

v1.31.0
